management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: info
    org.springframework.kafka: fatal
    com.voxxeddays.cern: debug

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/voxxeddays
    username: user
    password: pass

  kafka:
    listener:
      missingTopicsFatal: false
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      properties.spring.json.trusted.packages: com.voxxeddays.cern
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    bootstrap-servers: "localhost:9092"
















---
spring:
  docker:
    compose:
      enabled: false
      lifecycle-management: start_only
